# -*- coding: utf-8 -*-

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_PatracDockWidget(object):
    def setupUi(self, PatracDockWidget):
        PatracDockWidget.setObjectName(_fromUtf8("PatracDockWidget"))
        PatracDockWidget.resize(302, 182)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))

        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        
        #self.horizontalLayout_6 = QtGui.QHBoxLayout()
        #self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.comboPerson = QtGui.QComboBox(self.dockWidgetContents)
        self.comboPerson.setObjectName(_fromUtf8("comboPerson"))
        self.comboPerson.addItem(_fromUtf8(u"Dítě 1-3"))
        self.comboPerson.addItem(_fromUtf8(u"Dítě 4-6"))
        self.comboPerson.addItem(_fromUtf8(u"Dítě 7-12"))
        self.comboPerson.addItem(_fromUtf8(u"Dítě 13-15"))
        self.comboPerson.addItem(_fromUtf8(u"Deprese"))
        self.comboPerson.addItem(_fromUtf8(u"Psychická nemoc"))
        self.comboPerson.addItem(_fromUtf8(u"Retardovaný"))
        self.comboPerson.addItem(_fromUtf8(u"Alzheimer"))
        self.comboPerson.addItem(_fromUtf8(u"Turista"))
        self.comboPerson.addItem(_fromUtf8(u"Demence"))
        self.horizontalLayout_4.addWidget(self.comboPerson)
        #self.verticalLayout.addLayout(self.horizontalLayout_6)
        
        self.btnGetArea = QtGui.QPushButton(self.dockWidgetContents)
        self.btnGetArea.setObjectName(_fromUtf8("btnGetArea"))
        self.horizontalLayout_4.addWidget(self.btnGetArea)

        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.label = QtGui.QLabel(self.dockWidgetContents)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.sliderStart = QtGui.QSlider(self.dockWidgetContents)
        self.sliderStart.setProperty("value", 0)
        self.sliderStart.setOrientation(QtCore.Qt.Horizontal)
        self.sliderStart.setTickPosition(QtGui.QSlider.TicksBelow)
        self.sliderStart.setObjectName(_fromUtf8("sliderStart"))
        self.horizontalLayout.addWidget(self.sliderStart)
        self.spinStart = QtGui.QSpinBox(self.dockWidgetContents)
        self.spinStart.setMaximum(100)
        self.spinStart.setObjectName(_fromUtf8("spinStart"))
        self.horizontalLayout.addWidget(self.spinStart)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_2 = QtGui.QLabel(self.dockWidgetContents)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.sliderEnd = QtGui.QSlider(self.dockWidgetContents)
        self.sliderEnd.setOrientation(QtCore.Qt.Horizontal)
        self.sliderEnd.setTickPosition(QtGui.QSlider.TicksBelow)
        self.sliderEnd.setObjectName(_fromUtf8("sliderEnd"))
        self.horizontalLayout_2.addWidget(self.sliderEnd)
        self.spinEnd = QtGui.QSpinBox(self.dockWidgetContents)
        self.spinEnd.setObjectName(_fromUtf8("spinEnd"))
        self.horizontalLayout_2.addWidget(self.spinEnd)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.chkManualUpdate = QtGui.QCheckBox(self.dockWidgetContents)
        self.chkManualUpdate.setObjectName(_fromUtf8("chkManualUpdate"))
        self.horizontalLayout_3.addWidget(self.chkManualUpdate)
        self.btnRefresh = QtGui.QPushButton(self.dockWidgetContents)
        self.btnRefresh.setObjectName(_fromUtf8("btnRefresh"))
        self.horizontalLayout_3.addWidget(self.btnRefresh)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.btnGetSectors = QtGui.QPushButton(self.dockWidgetContents)
        self.btnGetSectors.setObjectName(_fromUtf8("btnGetSectors"))
        self.btnRecalculateSectors = QtGui.QPushButton(self.dockWidgetContents)
        self.btnRecalculateSectors.setObjectName(_fromUtf8("btnRecalculateSectors"))
        self.horizontalLayout_5.addWidget(self.btnGetSectors)
        self.horizontalLayout_5.addWidget(self.btnRecalculateSectors)              
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.btnExportSectors = QtGui.QPushButton(self.dockWidgetContents)
        self.btnExportSectors.setObjectName(_fromUtf8("btnExportSectors"))
        self.horizontalLayout_6.addWidget(self.btnExportSectors)
        self.btnShowSettings = QtGui.QPushButton(self.dockWidgetContents)
        self.btnShowSettings.setObjectName(_fromUtf8("btnShowSettings"))
        self.horizontalLayout_6.addWidget(self.btnShowSettings)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.btnImportGpx = QtGui.QPushButton(self.dockWidgetContents)
        self.btnImportGpx.setObjectName(_fromUtf8("btnImportGpx"))
        self.horizontalLayout_7.addWidget(self.btnImportGpx)
        self.btnShowPeople = QtGui.QPushButton(self.dockWidgetContents)
        self.btnShowPeople.setObjectName(_fromUtf8("btnShowPeople"))
        self.horizontalLayout_7.addWidget(self.btnShowPeople)
        self.btnShowMessage = QtGui.QPushButton(self.dockWidgetContents)
        self.btnShowMessage.setObjectName(_fromUtf8("btnShowMessage"))
        self.horizontalLayout_7.addWidget(self.btnShowMessage)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        PatracDockWidget.setWidget(self.dockWidgetContents)
        self.retranslateUi(PatracDockWidget)
        QtCore.QMetaObject.connectSlotsByName(PatracDockWidget)

    def retranslateUi(self, PatracDockWidget):
        PatracDockWidget.setWindowTitle(QtGui.QApplication.translate("PatracDockWidget", "Oblast", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("PatracDockWidget", "Hodnoty min/max", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("PatracDockWidget", "Hodnoty max/min", None, QtGui.QApplication.UnicodeUTF8))
        self.chkManualUpdate.setText(QtGui.QApplication.translate("PatracDockWidget", "Ruční aktualizace", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRefresh.setText(QtGui.QApplication.translate("PatracDockWidget", "Aktualizovat", None, QtGui.QApplication.UnicodeUTF8))
        self.btnGetArea.setText(QtGui.QApplication.translate("PatracDockWidget", "Určit prostor", None, QtGui.QApplication.UnicodeUTF8))
        self.btnGetSectors.setText(QtGui.QApplication.translate("PatracDockWidget", "Vybrat sektory", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRecalculateSectors.setText(QtGui.QApplication.translate("PatracDockWidget", "Přečíslovat sektory", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExportSectors.setText(QtGui.QApplication.translate("PatracDockWidget", "Exportovat sektory", None, QtGui.QApplication.UnicodeUTF8))
        self.btnShowSettings.setText(QtGui.QApplication.translate("PatracDockWidget", "Nastavení", None, QtGui.QApplication.UnicodeUTF8))
        self.btnImportGpx.setText(QtGui.QApplication.translate("PatracDockWidget", "Import GPX", None, QtGui.QApplication.UnicodeUTF8))
        self.btnShowPeople.setText(QtGui.QApplication.translate("PatracDockWidget", "Ukázat pátrače", None, QtGui.QApplication.UnicodeUTF8))
        self.btnShowMessage.setText(QtGui.QApplication.translate("PatracDockWidget", "Zprávy", None, QtGui.QApplication.UnicodeUTF8))

